### ISSUE TITLE
[Question] - Retrieve Transcoders by Livestream ID?

### ISSUE THREAD

**Issue by champsupertramp** [Ticketpark/WowzaWscRestPhp#1]
Hi @sprain 

Thank you for this Wowza REST API library. It really helped me with my projects.

I have a question which is related to the transcoders.

Could you please tell me how Wowza retrieves the Transcoder by Livestream Targets? Which ID does trancoders reference the Live stream?

Regards,

**Comment by sprain** [comment]
I am not sure, but if I remember correctly, you can't …

The API docs are here if that helps:
https://api.docs.cloud.wowza.com/current/
