### ISSUE TITLE
[Question] Possible to get stream state via FetchAllRequest?

### ISSUE THREAD

**Issue by Finn84FIN** [Ticketpark/WowzaWscRestPhp#10]
Hi,

I'm somewhat new to php still, but been playing around with this library a bit. I'm trying to build a table of available livestreams and was wondering how would you go about getting all stream IDs and the stream states for example? I seem to be able to first fetch all streams, and loop through those. Inside the loop, getId and then create a new object for the LiveStreamState. Is this the best approach or am I missing something? Feels unnecessarily slow.

Thanks.

**Comment by sprain** [comment]
This library does not support a different approach and I do not know whether Wowza would have a way to do otherwise. You can check their API: https://api.docs.cloud.wowza.com
