### ISSUE TITLE
Feature proposal: Analytics support

### ISSUE THREAD

**Issue by Finn84FIN** [Ticketpark/WowzaWscRestPhp#11]
Hello there,
This has been really helpful library for me and just wanted to ask if you have any plans to add analytics operations support at any point (/usage/)?

**Comment by sprain** [comment]
No plans, but well done PRs would be accepted.

**Comment by sprain** [comment]
Please note that this library will no longer be maintained. You are welcome to fork it to continue using it and add your own features.
