### ISSUE TITLE
Wowza REST API update

### ISSUE THREAD

**Issue by Finn84FIN** [Ticketpark/WowzaWscRestPhp#12]
Hi, it seems Wowza is deprecating v1.8 pretty soon and was wondering if you had plans to update this library? Biggest change is the use of API keys is no longer available. Will need to move to JSON Web Token.

**Comment by sprain** [comment]
Pull requests are welcome :)

**Comment by sprain** [comment]
Please note that this library will no longer be maintained. You are welcome to fork it to continue using it and add your own features.
