### ISSUE TITLE
Upgrade API to current version 1.5

### ISSUE THREAD

**Issue by champsupertramp** [Ticketpark/WowzaWscRestPhp#2]
Hi @sprain 

I would like to know how you would change the API version without modifying the vendor files? I would like to use the Wowza API version 1.5 to enable the VOD Stream option.

I can see that the [/Request.php](https://github.com/Ticketpark/WowzaWscRestPhp/blob/master/lib/Wsc/Request/Request.php#L23-L24) file  have the constant for API endpoints.

I'm able to add the VOD Stream in the container directly but it's not a good practice to modify it as a vendor.

Any help would be greatly appreaciated. Thanks for your open-source work.

Regards,

**Comment by sprain** [comment]
> I would like to know how you would change the API version without modifying the vendor files?

The best way would be to create a pull request so we can upgrade this library to use v1.5.
Of course, this needs to take care of [any potential changes that happened](https://www.wowza.com/docs/wowza-streaming-cloud-rest-api-release-notes) in the existing implementations.

**Comment by champsupertramp** [comment]
Hi @sprain  i created a pull request for initial changes to allow modification for Wowza API version. 

Sample usage:
```
$response = (new UpdateRequest($apiKey, $accessKey, false))
               ->setVersion("v1.5")
               ->setLiveStream($liveStream)
               ->execute();
```

See: https://github.com/Ticketpark/WowzaWscRestPhp/pull/3/commits/5a9cb553ccb7e2d8657c77425d60374b729aed5b

Regards,

**Comment by sprain** [comment]
> I created a pull request for initial changes to allow modification for Wowza API version.

See #3 for discussion on this.
